Video lib initial frontend done
theshivamverma/video-library-app pull request #1
Opened 2021-05-06 12:18 UTC by theshivamverma

2021-05-07 19:52 UTC, h-harsh requested changes

2021-05-07 19:52 UTC, h-harsh commented on README.old.md
> +### This repo is for video library app
More description to readme file can be given

2021-05-07 19:52 UTC, h-harsh commented on src/App.js
> +import VideoPage from "./components/VideoPage";
Make a better file structure and use index file for importing them all at once

2021-05-07 19:52 UTC, h-harsh commented on src/components/Topnavbar/Topnavbar.js
> +        <i class="fas fa-bars icon-med"></i>
className has to be used instead of class

2021-05-07 19:52 UTC, h-harsh commented on src/components/VideoCard.js
> +          class="btn btn-icon ml-1"
use className instead of class

2021-05-07 19:52 UTC, h-harsh commented on src/components/VideoList.js
> +// ];
remove unused code

2021-05-07 19:52 UTC, h-harsh commented on src/components/playlist/Playlist.js
> +                      {playlistItem.videos.map((video) => {
destructure element in map

2021-05-08 10:58 UTC, Akshay-Laxmipathi commented
Try to implement a feature that prevents users from creating a new playlist with an existing playlist name.

2021-11-20 12:31 UTC, merged